/*global systemDictionary:true */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
'use strict';

systemDictionary = {
  "Auto": {
    "en": "Auto",
    "de": "Auto",
    "ru": "Автоматически",
    "pt": "Auto",
    "nl": "Auto",
    "fr": "Auto",
    "it": "Auto",
    "es": "Auto",
    "pl": "Automatyczny",
    "uk": "Авто",
    "zh-cn": "汽车"
  },
  "Manual": {
    "en": "Manual",
    "de": "Manual",
    "ru": "Вручную",
    "pt": "Manual",
    "nl": "Met de hand",
    "fr": "Manuel",
    "it": "Manuale",
    "es": "Manual",
    "pl": "podręcznik",
    "uk": "Інструкція",
    "zh-cn": "手动的"
  },
  "My select": {
    "en": "My select",
    "de": "Mein Auswahl",
    "ru": "Выбор",
    "pt": "Meu selecionado",
    "nl": "Mijn select",
    "fr": "Mon choix",
    "it": "La mia selezione",
    "es": "Mi seleccion",
    "pl": "Mój wybór",
    "uk": "Мій вибір",
    "zh-cn": "我的选择"
  },
  "on save adapter restarts with new config immediately": {
    "en": "on save adapter restarts with new config immediately",
    "de": "Beim Speichern von Einstellungen der Adapter wird sofort neu gestartet.",
    "ru": "При сохранении настроек адаптера он сразу же перезапускается",
    "pt": "no adaptador de salvar reinicia com nova configuração imediatamente",
    "nl": "on save-adapter wordt onmiddellijk opnieuw opgestart met nieuwe config",
    "fr": "sur l'adaptateur de sauvegarde redémarre avec la nouvelle config immédiatement",
    "it": "su save adapter si riavvia immediatamente con la nuova configurazione",
    "es": "en el adaptador de guardar se reinicia con nueva configuración de inmediato",
    "pl": "po zapisaniu adapter natychmiast uruchamia się ponownie z nową konfiguracją",
    "uk": "під час збереження адаптер негайно перезавантажується з новою конфігурацією",
    "zh-cn": "保存适配器后立即使用新配置重新启动"
  },
  "template adapter settings": {
    "en": "template adapter settings",
    "de": "Beispiel",
    "ru": "Пример",
    "pt": "configurações do adaptador de modelo",
    "nl": "sjabloon-adapterinstellingen",
    "fr": "paramètres de l'adaptateur de modèle",
    "it": "impostazioni dell'adattatore del modello",
    "es": "configuración del adaptador de plantilla",
    "pl": "ustawienia adaptera szablonu",
    "uk": "налаштування адаптера шаблону",
    "zh-cn": "模板适配器设置"
  },
  "host": {
    "en": "Confoair IP:",
    "de": "Comfoair IP:",
    "ru": "Соларлог IP:",
    "pt": "IP Confoair:",
    "nl": "Confoair-IP:",
    "fr": "IP du Confoair :",
    "it": "IP Solarlog:",
    "es": "IP de SolarLog:",
    "pl": "Adres IP Solarloga:",
    "uk": "Solarlog IP:",
    "zh-cn": "太阳能日志IP："
  },
  "pollInterval": {
    "en": "Polling - Interval (ms):",
    "de": "Abfrage - Intervall (ms):",
    "ru": "Опрос - Интервал (мс):",
    "pt": "Pesquisa - Intervalo (ms):",
    "nl": "Polling - Interval (ms):",
    "fr": "Interrogation - Intervalle (ms) :",
    "it": "Polling - Intervallo (ms):",
    "es": "Sondeo - Intervalo (ms):",
    "pl": "Odpytywanie — interwał (ms):",
    "uk": "Опитування - Інтервал (мс):",
    "zh-cn": "轮询 - 间隔（毫秒）："
  },
  "port": {
    "en": "Port",
    "de": "Port",
    "ru": "Порт",
    "pt": "Porta",
    "nl": "Haven",
    "fr": "Port",
    "it": "Porta",
    "es": "Puerto",
    "pl": "Port",
    "uk": "Порт",
    "zh-cn": "港口"
  }
};
