// DO NOT EDIT THIS FILE!!! IT WILL BE AUTOMATICALLY GENERATED FROM src/i18n
/*global systemDictionary:true */
'use strict';

systemDictionary = {
  "Auto": {
    "en": "Auto",
    "de": "Auto",
    "ru": "Auto",
    "pt": "Auto",
    "nl": "Auto",
    "fr": "Auto",
    "it": "Auto",
    "es": "Auto"
  },
  "Manual": {
    "en": "Manual",
    "de": "Manual",
    "ru": "Manual",
    "pt": "Manual",
    "nl": "Met de hand",
    "fr": "Manuel",
    "it": "Manuale",
    "es": "Manual"
  },
  "My select": {
    "en": "My select",
    "de": "Mein Auswahl",
    "ru": "My select",
    "pt": "Meu selecionado",
    "nl": "Mijn select",
    "fr": "Mon choix",
    "it": "La mia selezione",
    "es": "Mi seleccion"
  },
  "on save adapter restarts with new config immediately": {
    "en": "on save adapter restarts with new config immediately",
    "de": "Beim Speichern von Einstellungen der Adapter wird sofort neu gestartet.",
    "ru": "on save adapter restarts with new config immediately",
    "pt": "no adaptador de salvar reinicia com nova configuraÃ§Ã£o imediatamente",
    "nl": "on save-adapter wordt onmiddellijk opnieuw opgestart met nieuwe config",
    "fr": "sur l'adaptateur de sauvegarde redÃ©marre avec la nouvelle config immÃ©diatement",
    "it": "su save adapter si riavvia immediatamente con la nuova configurazione",
    "es": "en el adaptador de guardar se reinicia con nueva configuraciÃ³n de inmediato"
  },
  "template adapter settings": {
    "en": "template adapter settings",
    "de": "Beispiel",
    "ru": "template adapter settings",
    "pt": "configuraÃ§Ãµes do adaptador de modelo",
    "nl": "sjabloon-adapterinstellingen",
    "fr": "paramÃ¨tres de l'adaptateur de modÃ¨le",
    "it": "impostazioni dell'adattatore del modello",
    "es": "configuraciÃ³n del adaptador de plantilla"
  },
  "luxtronik1 adapter settings": {
    "en": "Luxtronik 1 adapter settings",
    "de": "Luxtronik 1 Adaptereinstellungen",
    "ru": "Настройки адаптера Luxtronik 1",
    "pt": "Configurações do adaptador Luxtronik 1",
    "nl": "Luxtronik 1 adapterinstellingen",
    "fr": "Paramètres de l'adaptateur Luxtronik 1",
    "it": "Impostazioni dell'adattatore Luxtronik 1",
    "es": "Configuración del adaptador Luxtronik 1"
  },
  "port": {
    "en": "port",
    "de": "Port",
    "ru": "порт",
    "pt": "porta",
    "nl": "haven",
    "fr": "Port",
    "it": "porta",
    "es": "Puerto"
  },
  "host": {
    "en": "Luxtronik1 IP:",
    "de": "Luxtronik1 IP:",
    "ru": "Luxtronik1 IP:",
    "pt": "Luxtronik1 IP:",
    "nl": "Luxtronik1 IP:",
    "fr": "Luxtronik1 IP:",
    "it": "Luxtronik1 IP:",
    "es": "Luxtronik1 IP:"
  },
  "pollInterval": {
    "en": "Polling - intervall (ms):",
    "de": "Polling - Intervall (ms):",
    "ru": "Опрос - интервал (мс):",
    "pt": "Intervalo de pesquisa - (ms):",
    "nl": "Polling - intervall (ms):",
    "fr": "Interrogation - intervalle (ms):",
    "it": "Polling - intervall (ms):",
    "es": "Sondeo - intervalo (ms):"
  }
}
